---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: krypteau_dev
  :username: root
  :password: 
  :host: localhost
  :socket: /tmp/mysql.sock
  :encoding: utf8

:test:
  <<: *defaults
  :database: krypteau_test

#:production:
#  <<: *defaults
#  :database: sample_production
